version: '2'
services:

  frontend:
    env_file:
      - vars.env
    container_name: as_frontend
    build: ./src/AliseeksFE/bin/Release/netcoreapp1.0/publish
    ports:
      - "${ALISEEKSFE_PORTMAP}:${ALISEEKSFE_PORT}"
    external_links:
      - as_api
