using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AliseeksFE.Injectables.Search
{
    public class SearchCriteriaInject
    {
        public Dictionary<string, string> GetShipToCountries()
        {
            var countries = new Dictionary<string, string>()
            {
                { "Any", "" },
                { "United Kingdom", "UK" },
                { "Spain", "ES" },
                { "Germany", "DE" },
                { "France", "FR" },
                { "Italy", "IT" },
                { "China (Mainland)", "CN" }
            };

            return countries;
        }

        //Don't open this
        public Dictionary<string, string> GetShipFromCountries()
        {
            var countries = new Dictionary<string, string>()
            {
                {"United States","US"},
                {"Any","all"},
                {"Russian Federation","RU"},
                {"Brazil","BR"},
                {"Australia","AU"},
                {"United Kingdom","UK"},
                {"Spain","ES"},
                {"France","FR"},
                {"Canada","CA"},
                {"Poland","PL"},
                {"Turkey","TR"},
                {"Sweden","SE"},
                {"Israel","IL"},
                {"Italy","IT"},
                {"New Zealand","NZ"},
                {"Germany","DE"},
                {"Afghanistan","AF"},
                {"Aland Islands","ALA"},
                {"Albania","AL"},
                {"Alderney","GBA"},
                {"Algeria","DZ"},
                {"American Samoa","AS"},
                {"Andorra","AD"},
                {"Angola","AO"},
                {"Anguilla","AI"},
                {"Antigua and Barbuda","AG"},
                {"Argentina","AR"},
                {"Armenia","AM"},
                {"Aruba","AW"},
                {"Ascension Island","ASC"},
                {"Austria","AT"},
                {"Azerbaijan","AZ"},
                {"Bahamas","BS"},
                {"Bahrain","BH"},
                {"Bangladesh","BD"},
                {"Barbados","BB"},
                {"Belarus","BY"},
                {"Belgium","BE"},
                {"Belize","BZ"},
                {"Benin","BJ"},
                {"Bermuda","BM"},
                {"Bhutan","BT"},
                {"Bolivia","BO"},
                {"Bosnia and Herzegovina","BA"},
                {"Botswana","BW"},
                {"Brunei Darussalam","BN"},
                {"Bulgaria","BG"},
                {"Burkina Faso","BF"},
                {"Burundi","BI"},
                {"Cambodia","KH"},
                {"Cameroon","CM"},
                {"Cape Verde","CV"},
                {"Cayman Islands","KY"},
                {"Central African Republic","CF"},
                {"Chad","TD"},
                {"Chile","CL"},
                {"Christmas Island","CX"},
                {"Cocos (Keeling) Islands","CC"},
                {"Colombia","CO"},
                {"Comoros","KM"},
                {"Congo","CG"},
                {"Cook Islands","CK"},
                {"Costa Rica","CR"},
                {"Cote D&#39;Ivoire","CI"},
                {"Croatia (local name: Hrvatska)","HR"},
                {"Cuba","CU"},
                {"Cyprus","CY"},
                {"Czech Republic","CZ"},
                {"Denmark","DK"},
                {"Djibouti","DJ"},
                {"Dominica","DM"},
                {"Dominican Republic","DO"},
                {"East Timor","TP"},
                {"Ecuador","EC"},
                {"Egypt","EG"},
                {"El Salvador","SV"},
                {"Equatorial Guinea","GQ"},
                {"Eritrea","ER"},
                {"Estonia","EE"},
                {"Ethiopia","ET"},
                {"Falkland Islands (Malvinas)","FK"},
                {"Faroe Islands","FO"},
                {"Fiji","FJ"},
                {"Finland","FI"},
                {"French Guiana","GF"},
                {"French Polynesia","PF"},
                {"Gabon","GA"},
                {"Gambia","GM"},
                {"Georgia","GE"},
                {"Ghana","GH"},
                {"Gibraltar","GI"},
                {"Greece","GR"},
                {"Greenland","GL"},
                {"Grenada","GD"},
                {"Guadeloupe","GP"},
                {"Guam","GU"},
                {"Guatemala","GT"},
                {"Guernsey","GGY"},
                {"Guinea","GN"},
                {"Guinea-Bissau","GW"},
                {"Guyana","GY"},
                {"Haiti","HT"},
                {"Honduras","HN"},
                {"Hong Kong","HK"},
                {"Hungary","HU"},
                {"Iceland","IS"},
                {"India","IN"},
                {"Indonesia","ID"},
                {"Iran (Islamic Republic of)","IR"},
                {"Iraq","IQ"},
                {"Ireland","IE"},
                {"Jamaica","JM"},
                {"Japan","JP"},
                {"Jersey","JEY"},
                {"Jordan","JO"},
                {"Kazakhstan","KZ"},
                {"Kenya","KE"},
                {"Kiribati","KI"},
                {"Kuwait","KW"},
                {"Kyrgyzstan","KG"},
                {"Lao People&#39;s Democratic Republic","LA"},
                {"Latvia","LV"},
                {"Lebanon","LB"},
                {"Lesotho","LS"},
                {"Liberia","LR"},
                {"Libya","LY"},
                {"Liechtenstein","LI"},
                {"Lithuania","LT"},
                {"Luxembourg","LU"},
                {"Macau","MO"},
                {"Macedonia","MK"},
                {"Madagascar","MG"},
                {"Malawi","MW"},
                {"Malaysia","MY"},
                {"Maldives","MV"},
                {"Mali","ML"},
                {"Malta","MT"},
                {"Marshall Islands","MH"},
                {"Martinique","MQ"},
                {"Mauritania","MR"},
                {"Mauritius","MU"},
                {"Mayotte","YT"},
                {"Mexico","MX"},
                {"Micronesia","FM"},
                {"Moldova","MD"},
                {"Monaco","MC"},
                {"Mongolia","MN"},
                {"Montenegro","MNE"},
                {"Montserrat","MS"},
                {"Morocco","MA"},
                {"Mozambique","MZ"},
                {"Myanmar","MM"},
                {"Namibia","NA"},
                {"Nauru","NR"},
                {"Nepal","NP"},
                {"Netherlands","NL"},
                {"Netherlands Antilles","AN"},
                {"New Caledonia","NC"},
                {"Nicaragua","NI"},
                {"Niger","NE"},
                {"Nigeria","NG"},
                {"Niue","NU"},
                {"Norfolk Island","NF"},
                {"North Korea","KP"},
                {"Northern Mariana Islands","MP"},
                {"Norway","NO"},
                {"Oman","OM"},
                {"Other Country","Other"},
                {"Pakistan","PK"},
                {"Palau","PW"},
                {"Palestine","PS"},
                {"Panama","PA"},
                {"Papua New Guinea","PG"},
                {"Paraguay","PY"},
                {"Peru","PE"},
                {"Philippines","PH"},
                {"Portugal","PT"},
                {"Puerto Rico","PR"},
                {"Qatar","QA"},
                {"Reunion","RE"},
                {"Romania","RO"},
                {"Rwanda","RW"},
                {"Saint Barthelemy","BLM"},
                {"Saint Kitts and Nevis","KN"},
                {"Saint Lucia","LC"},
                {"Saint Martin","MAF"},
                {"Saint Vincent and the Grenadines","VC"},
                {"Samoa","WS"},
                {"San Marino","SM"},
                {"Sao Tome and Principe","ST"},
                {"Saudi Arabia","SA"},
                {"Scotland","SCT"},
                {"Senegal","SN"},
                {"Serbia","SRB"},
                {"Seychelles","SC"},
                {"Sierra Leone","SL"},
                {"Singapore","SG"},
                {"Slovakia (Slovak Republic)","SK"},
                {"Slovenia","SI"},
                {"Solomon Islands","SB"},
                {"Somalia","SO"},
                {"South Africa","ZA"},
                {"South Georgia and the South Sandwich Islands","SGS"},
                {"South Korea","KR"},
                {"South Sudan","SS"},
                {"Sri Lanka","LK"},
                {"St. Pierre and Miquelon","PM"},
                {"Sudan","SD"},
                {"Suriname","SR"},
                {"Swaziland","SZ"},
                {"Switzerland","CH"},
                {"Syrian Arab Republic","SY"},
                {"Taiwan","TW"},
                {"Tajikistan","TJ"},
                {"Tanzania","TZ"},
                {"Thailand","TH"},
                {"Timor-Leste","TLS"},
                {"Togo","TG"},
                {"Tonga","TO"},
                {"Trinidad and Tobago","TT"},
                {"Tunisia","TN"},
                {"Turkmenistan","TM"},
                {"Turks and Caicos Islands","TC"},
                {"Tuvalu","TV"},
                {"Uganda","UG"},
                {"Ukraine","UA"},
                {"United Arab Emirates","AE"},
                {"Uruguay","UY"},
                {"Uzbekistan","UZ"},
                {"Vanuatu","VU"},
                {"Vatican City State (Holy See)","VA"},
                {"Venezuela","VE"},
                {"Vietnam","VN"},
                {"Virgin Islands (British)","VG"},
                {"Virgin Islands (U.S.)","VI"},
                {"Wallis And Futuna Islands","WF"},
                {"Yemen","YE"},
                {"Yugoslavia","YU"},
                {"Zambia","ZM"},
                {"Zanzibar","EAZ"},
                {"Zimbabwe","ZW"}
            };

            return countries;
        }
    }
}
